name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-process:
    name: CI Process
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SonarQube Scanner
      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          token: ${{ secrets.SONAR_TOKEN }}

      # Step 3: Run SonarQube Scan
      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t sandhya0593/netflix:latest .

      # Step 5: Run Trivy Scan
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: sandhya0593/netflix:latest

     

      # Step 6: Push Docker Image to Docker Repository
      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag your-docker-image:latest sandhya0593/netflix:latest
          docker push sandhya0593/netflix:latest